### ISSUE TITLE
Add a setting to increase and decrease the number or percent 40s

### ISSUE THREAD

**Issue by ghost** [BOBLO123/silly-40-buttons#2] opened 2024-10-29 16:45 UTC
Reason: Some people's shitty chromebooks just can't cope with all the percent 40. They need less so it doesn't lag out their chromebook. You could even run a test to render an image that the user cant see or something and see how fast it goes and then choose it automatically then have the user change it if they want to.

**Comment by ipushthecarts** [comment] 2024-10-29 16:46
thank you for making a issue, but its not really possible to my knowledge, but we can add it to the testing branch and you can test when we add it, sound good?

**Comment by ipushthecarts** [comment] 2024-10-29 16:49
also, read the pinned issue before making a issue, professionalism exists and is helpful to me. thanks!

**Comment by ipushthecarts** [comment] 2024-10-29 18:03
this will be closed for now, and for future reference, the closed issue will be in the "closed" tab

**Closed as completed by ipushthecarts** 2024-10-29 18:03 UTC

**Comment by Raf128** [comment] 2024-10-29 20:06
I can confirm that a lower number of characters works as intended. After more testing this will be added in our next release.

Edit:
This can be scaled down to a minimum of 350 to work properly, any lower will be parsed by most extensions. (I only tested one, but it should still work on others) Therefore, the function will have a fixed value of 350.
